<script setup>
/* import the fontawesome core */
import { library } from "@fortawesome/fontawesome-svg-core";

/* import font awesome icon component */
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

/* import specific icons */
import {
  faFacebook,
  faInstagram,
  faTiktok,
  faTwitter,
} from '@fortawesome/free-brands-svg-icons';

import {
  fa1,
  fa2,
  fa3,
  faAddressCard,
  faAngleDown,
  faAngleUp,
  faAlignCenter,
  faAlignJustify,
  faAlignLeft,
  faAlignRight,
  faArrowRightLong,
  faArrowRotateLeft,
  faBars,
  faBroom,
  faBold,
  faCaretDown,
  faCaretLeft,
  faCaretRight,
  faCaretUp,
  faCircleUp,
  faColumns,
  faCompress,
  faEnvelope,
  faEye,
  faFloppyDisk,
  faFolderPlus,
  faHeading,
  faHouse,
  faImage,
  faItalic,
  faLink,
  faListOl,
  faListUl,
  faLocationDot,
  faMagnifyingGlass,
  faMoon,
  faNewspaper,
  faParagraph,
  faPenToSquare,
  faPlus,
  faPhone,
  faRedoAlt,
  faSchool,
  faScroll,
  faStrikethrough,
  faSun,
  faTable,
  faTimes,
  faTrash,
  faUnderline,
  faUndoAlt,
  faQuoteLeft,
} from "@fortawesome/free-solid-svg-icons";

/* add icons to the library */
library.add(
  faFacebook,
  faInstagram,
  faTiktok,
  faTwitter,
  fa1,
  fa2,
  fa3,
  faAddressCard,
  faAngleDown,
  faAngleUp,
  faAlignCenter,
  faAlignJustify,
  faAlignLeft,
  faAlignRight,
  faArrowRightLong,
  faArrowRotateLeft,
  faBars,
  faBroom,
  faBold,
  faCaretDown,
  faCaretLeft,
  faCaretRight,
  faCaretUp,
  faCircleUp,
  faColumns,
  faCompress,
  faEnvelope,
  faEye,
  faFloppyDisk,
  faFolderPlus,
  faHeading,
  faHouse,
  faImage,
  faItalic,
  faLink,
  faListOl,
  faListUl,
  faLocationDot,
  faMagnifyingGlass,
  faMoon,
  faNewspaper,
  faParagraph,
  faPenToSquare,
  faPhone,
  faPlus,
  faRedoAlt,
  faSchool,
  faScroll,
  faStrikethrough,
  faSun,
  faTable,
  faTimes,
  faTrash,
  faUnderline,
  faUndoAlt,
  faQuoteLeft
);
</script>

<template>
  <FontAwesomeIcon></FontAwesomeIcon>
</template>